### PR TITLE
Change Config file and Change my stepdefination file and Feautre file

### PR DESCRIPTION
**Pull request by singhvishubham**

### CODE REVIEW

**Comment by asksleo** [comment]
Shubham bhai is branch me conflict aa rhe hai

**Comment by singhvishubham** [comment]
Remove the conflict and Create new Changes

**Review by Prashantji007 — APPROVED** [review]
Approved Resolved conflict by shubham

**Comment by Prashantji007** [comment]
I'm merging the Pull request 21 by Shubham @asksleo

**Pull request merged**
